# Generated by Django 4.2.7 on 2023-12-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AWSAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_key_id", models.CharField(max_length=80)),
                ("access_secret_key_id", models.CharField(max_length=80)),
            ],
        ),
    ]
